import fastify from "fastify";
import path from "path";
import { initDatabase, closeDatabase, cleanupExpiredMemories } from "./db.js";
import { registerRoutes, setCoordinatorClient } from "./routes.js";
import { createCoordinatorClient, type CoordinatorClient } from "./coordinator-client.js";
import { logger } from "./logger.js";

const DEFAULT_PORT = 3457;
const DEFAULT_HOST = "0.0.0.0";
const DEFAULT_CONFIG_DIR = "./config";
const DEFAULT_DB_FILENAME = "drone-beacon.db";

interface Config {
  port: number;
  host: string;
  configDir: string;
  dbPath: string;
  coordinatorHost?: string;
  coordinatorPort?: number;
  beaconId: string;
  beaconName: string;
}

function parseArgs(): Config {
  const args = process.argv.slice(2);
  const config: Config = {
    port: DEFAULT_PORT,
    host: DEFAULT_HOST,
    configDir: DEFAULT_CONFIG_DIR,
    dbPath: path.join(DEFAULT_CONFIG_DIR, DEFAULT_DB_FILENAME),
    beaconId: `beacon-${Date.now()}`,
    beaconName: "default-beacon",
  };

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (arg === "--port" && i + 1 < args.length) {
      config.port = parseInt(args[++i], 10);
    } else if (arg === "--host" && i + 1 < args.length) {
      config.host = args[++i];
    } else if (arg === "--db" && i + 1 < args.length) {
      config.dbPath = args[++i];
    } else if (arg === "--config-dir" && i + 1 < args.length) {
      config.configDir = args[++i];
      // Update dbPath to be relative to the new config dir
      config.dbPath = path.join(config.configDir, DEFAULT_DB_FILENAME);
    } else if (arg === "--coordinator-host" && i + 1 < args.length) {
      config.coordinatorHost = args[++i];
    } else if (arg === "--coordinator-port" && i + 1 < args.length) {
      config.coordinatorPort = parseInt(args[++i], 10);
    } else if (arg === "--id" && i + 1 < args.length) {
      config.beaconId = args[++i];
    } else if (arg === "--name" && i + 1 < args.length) {
      config.beaconName = args[++i];
    } else if (arg === "--help" || arg === "-h") {
      console.log(`
drone-beacon [options]

Options:
  --port <n>              Port to listen on (default: ${DEFAULT_PORT})
  --host <h>              Host to bind to (default: ${DEFAULT_HOST})
  --config-dir <dir>      Configuration directory (default: ${DEFAULT_CONFIG_DIR})
  --db <path>             Path to SQLite database (default: <config-dir>/${DEFAULT_DB_FILENAME})
  --coordinator-host <h>   Host of the coordinator to connect to
  --coordinator-port <n>  Port of the coordinator (default: ${DEFAULT_PORT + 1})
  --id <id>               Beacon ID (auto-generated by default)
  --name <name>           Beacon name (default: default-beacon)
  --help                  Show this help message
      `);
      process.exit(0);
    }
  }

  // Default coordinator port if not specified but host is provided
  if (config.coordinatorHost && !config.coordinatorPort) {
    config.coordinatorPort = DEFAULT_PORT + 1;
  }

  return config;
}

async function main() {
  const config = parseArgs();

  logger.info(`Starting drone-beacon on ${config.host}:${config.port}`);
  logger.info(`Configuration directory: ${config.configDir}`);
  logger.info(`Database path: ${config.dbPath}`);

  // Initialize database
  initDatabase(config.dbPath);

  // Set up coordinator client if configured
  let coordinatorClient: CoordinatorClient | undefined;
  if (config.coordinatorHost && config.coordinatorPort) {
    coordinatorClient = createCoordinatorClient({
      host: config.coordinatorHost,
      port: config.coordinatorPort,
      beaconId: config.beaconId,
      beaconName: config.beaconName,
    });
    setCoordinatorClient(coordinatorClient);

    try {
      await coordinatorClient.registerBeacon({
        host: config.host,
        port: config.port,
        beaconId: config.beaconId,
        beaconName: config.beaconName,
      });
    } catch (err) {
      logger.warn(`Failed to register with coordinator: ${err}. Running in offline mode.`);
    }
  }

  // Create Fastify instance
  const app = fastify({
    logger: logger,
  });

  // Register routes
  await registerRoutes(app);

  // Start periodic TTL cleanup (every minute)
  const cleanupInterval = setInterval(() => {
    try {
      cleanupExpiredMemories();
    } catch (err) {
      logger.error(err, "TTL cleanup failed");
    }
  }, 60000);

  // Graceful shutdown
  const shutdown = async () => {
    logger.info("Shutting down...");
    clearInterval(cleanupInterval);
    await app.close();
    closeDatabase();
    process.exit(0);
  };

  process.on("SIGINT", shutdown);
  process.on("SIGTERM", shutdown);

  // Start server
  try {
    await app.listen({ port: config.port, host: config.host });
    logger.info(`Beacon listening on http://${config.host}:${config.port}`);
  } catch (err) {
    logger.error(err);
    process.exit(1);
  }
}

main();