export const LIBRARIAN_PERSONA_ID = 'coordinator-wiki-librarian';

export type SwarmMemorySettings = {
  coordinatorUrl: string;
  webToken: string;
  configureBeacon: boolean;
  batchLimit: string;
  cronSchedule: string;
};

/**
 * Optional per-host env overrides (e.g. DRONE_COORDINATOR_WEB_TOKEN),
 * sourced by both generated scripts. Written only when a web token was
 * supplied during bootstrap; absent in the default loopback topology.
 */
export const ENV_SOURCE_BLOCK = `if [ -f "$HOME/.drone-swarm-memory/env" ]; then
  . "$HOME/.drone-swarm-memory/env"
fi`;

export const HOOK_SCRIPT_NAME = 'session-end-ingest.sh';
export const CATCHUP_SCRIPT_NAME = 'catch-up-ingest.sh';

/** Build the kick-off NDJSON event via node (guaranteed present beside drone-agent). */
const TRANSCRIPT_TO_KICKOFF =
  'node -e \'const fs=require("node:fs");const t=JSON.parse(fs.readFileSync(0,"utf8"));' +
  'process.stdout.write(JSON.stringify({type:"kickoff",task:t}))\'';

export function buildHookScript(settings: SwarmMemorySettings): string {
  return `#!/usr/bin/env bash
# Session-end ingest hook for the swarm memory pipeline.
# Generated by bootstrap__swarm-memory. The coordinator substitutes
# {session_id} and runs this with /bin/sh -c; exit code 0 = ingested.
set -euo pipefail

${ENV_SOURCE_BLOCK}

SESSION_ID="\${1:?usage: ${HOOK_SCRIPT_NAME} <session_id>}"
COORDINATOR_URL="${settings.coordinatorUrl}"
LIBRARIAN_PERSONA="${LIBRARIAN_PERSONA_ID}"

# Claim the session first (ended → processing) so concurrent runs skip it.
drone-swarm --coordinator "$COORDINATOR_URL" session process "$SESSION_ID" > /dev/null

# Self-ingest guard: the librarian must not ingest its own sessions.
# Skip = mark processed (NOT leave-as-ended, which would re-queue the
# session forever and starve the catch-up batch) and exit 0.
# session log returns the full { session: { personaId }, ... } envelope, so the
# persona is available here without spawning an agent. (session transcript
# prints only the transcript string, which has no persona — reading it there
# never matched, so every librarian session spawned an agent.)
session_persona="$(drone-swarm --coordinator "$COORDINATOR_URL" session log "$SESSION_ID" | node -e 'const fs=require("node:fs");const t=JSON.parse(fs.readFileSync(0,"utf8"));process.stdout.write(String(t.session && t.session.personaId || ""))')"
if [ "$session_persona" = "$LIBRARIAN_PERSONA" ]; then
  drone-swarm --coordinator "$COORDINATOR_URL" session processed "$SESSION_ID" \\
    --summary "skipped: librarian self-session (self-ingest guard)"
  echo "self-ingest guard: session $SESSION_ID is a $LIBRARIAN_PERSONA session; skipped"
  exit 0
fi

# Read the --- Turn N --- transcript and queue it to a headless librarian.
transcript_json="$(drone-swarm --coordinator "$COORDINATOR_URL" session transcript "$SESSION_ID")"

kickoff="$(printf '%s' "$transcript_json" | ${TRANSCRIPT_TO_KICKOFF})"

if printf '%s\\n' "$kickoff" | drone-agent --output-json --once --persona "$LIBRARIAN_PERSONA" > /dev/null 2>&1; then
  drone-swarm --coordinator "$COORDINATOR_URL" session processed "$SESSION_ID" \\
    --summary "ingested into memory wiki by ${HOOK_SCRIPT_NAME}"
else
  echo "librarian agent failed for session $SESSION_ID (left in processing)" >&2
  exit 1
fi
`;
}

export function buildCatchupScript(settings: SwarmMemorySettings): string {
  return `#!/usr/bin/env bash
# Gradual catch-up ingest for the swarm memory pipeline.
# Generated by bootstrap__swarm-memory. Grabs ended sessions newest-first
# (batch limited) and feeds each through the session-end ingest hook.
set -euo pipefail

${ENV_SOURCE_BLOCK}

COORDINATOR_URL="${settings.coordinatorUrl}"
BATCH_LIMIT="${settings.batchLimit}"
INGEST_HOOK="$HOME/.drone-swarm-memory/bin/${HOOK_SCRIPT_NAME}"
LIBRARIAN_PERSONA="${LIBRARIAN_PERSONA_ID}"

sessions_json="$(drone-swarm --coordinator "$COORDINATOR_URL" session list --status ended --limit "$BATCH_LIMIT")"
rows="$(printf '%s' "$sessions_json" | node -e 'const fs=require("node:fs");const d=JSON.parse(fs.readFileSync(0,"utf8"));for(const s of (d.sessions ?? []))process.stdout.write(String(s.id)+"\\t"+(s.personaId||"")+"\\n")')"

if [ -z "$rows" ]; then
  echo "catch-up: no ended sessions to ingest"
  exit 0
fi

failed=0
while IFS=$'\t' read -r id persona; do
  [ -n "$id" ] || continue
  if [ "$persona" = "$LIBRARIAN_PERSONA" ]; then
    drone-swarm --coordinator "$COORDINATOR_URL" session processed "$id" \
      --summary "skipped: librarian self-session (list-level guard)"
    echo "catch-up: dismissed librarian session $id"
    continue
  fi
  if ! bash "$INGEST_HOOK" "$id"; then
    echo "catch-up: ingest failed for session $id (continuing)" >&2
    failed=$((failed + 1))
  fi
done <<< "$rows"

echo "catch-up: batch complete ($failed failure(s))"
exit 0
`;
}
