import { spawn } from 'node:child_process';
import { constants as fsConstants } from 'node:fs';
import { access, chmod, mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import type { DroneElicitation, DroneWorkflow } from 'drone-core';
import { mergeConfig, validateConfigFile } from 'drone-swarm-common';

export type RunResult = { code: number; stdout: string; stderr: string };

export type CommandRunner = (
  cmd: string[],
  options?: { input?: string }
) => Promise<RunResult>;

const LIBRARIAN_PERSONA_ID = 'coordinator-wiki-librarian';
const MEMORY_DIR = '.drone-swarm-memory';
const DEFAULT_COORDINATOR_URL = 'http://localhost:3456';
const DEFAULT_BATCH_LIMIT = '5';
const DEFAULT_CRON_SCHEDULE = '0 * * * *';

export const HOOK_SCRIPT_NAME = 'session-end-ingest.sh';
export const CATCHUP_SCRIPT_NAME = 'catch-up-ingest.sh';

export type SwarmMemorySettings = {
  coordinatorUrl: string;
  configureBeacon: boolean;
  batchLimit: string;
  cronSchedule: string;
};

type Discovery = {
  settings: SwarmMemorySettings;
  coordinatorReachable: boolean;
  launchMode: 'systemd' | 'docker' | 'unknown';
  coordinatorConfigPath: string;
  beaconConfigPath: string;
  coordinatorConfigRaw: string | undefined;
  beaconConfigRaw: string | undefined;
};

type StepReport = {
  step: string;
  status: 'done' | 'skipped' | 'failed' | 'pending-restart-needed';
  detail?: string;
};

/** Default runner: node:child_process spawn with optional stdin input. */
export function createExecFileRunner(): CommandRunner {
  return (cmd, options) =>
    new Promise(resolve => {
      let stdout = '';
      let stderr = '';
      const child = spawn(cmd[0] ?? '', cmd.slice(1), {
        stdio: ['pipe', 'pipe', 'pipe'],
      });
      child.stdout?.on('data', (d: Buffer) => {
        stdout += String(d);
      });
      child.stderr?.on('data', (d: Buffer) => {
        stderr += String(d);
      });
      child.on('error', err => {
        resolve({ code: -1, stdout, stderr: String(err) });
      });
      child.on('close', code => {
        resolve({ code: code ?? -1, stdout, stderr });
      });
      if (options?.input !== undefined) {
        child.stdin?.write(options.input);
      }
      child.stdin?.end();
    });
}

export function hookScriptPath(home = os.homedir()): string {
  return path.join(home, MEMORY_DIR, 'bin', HOOK_SCRIPT_NAME);
}

export function catchupScriptPath(home = os.homedir()): string {
  return path.join(home, MEMORY_DIR, 'bin', CATCHUP_SCRIPT_NAME);
}

export function coordinatorConfigPath(home = os.homedir()): string {
  return path.join(home, '.drone-coordinator', 'config.json');
}

export function beaconConfigPath(home = os.homedir()): string {
  return path.join(home, '.drone-beacon', 'config.json');
}

async function exists(filePath: string): Promise<boolean> {
  try {
    await access(filePath, fsConstants.F_OK);
    return true;
  } catch {
    return false;
  }
}

async function readIfPresent(filePath: string): Promise<string | undefined> {
  if (!(await exists(filePath))) {
    return undefined;
  }
  return readFile(filePath, 'utf8');
}

/**
 * Atomic write: temp file + rename so a crash never leaves a truncated
 * config. Scripts get chmod 0755 (the umask would strip the exec bit).
 */
async function atomicWrite(
  filePath: string,
  content: string,
  mode?: number
): Promise<void> {
  await mkdir(path.dirname(filePath), { recursive: true });
  const tmp = `${filePath}.tmp-${process.pid}-${Date.now()}`;
  await writeFile(tmp, content, 'utf-8');
  if (mode !== undefined) {
    await chmod(tmp, mode);
  }
  await rename(tmp, filePath);
}

function parseJsonIfPossible(raw: string | undefined): unknown {
  if (raw === undefined) {
    return undefined;
  }
  try {
    return JSON.parse(raw) as unknown;
  } catch {
    return undefined;
  }
}

/** Build the kick-off NDJSON event via node (guaranteed present beside drone-agent). */
const TRANSCRIPT_TO_KICKOFF =
  'node -e \'const fs=require("node:fs");const t=JSON.parse(fs.readFileSync(0,"utf8"));' +
  'process.stdout.write(JSON.stringify({type:"kickoff",task:t}))\'';

export function buildHookScript(settings: SwarmMemorySettings): string {
  return `#!/usr/bin/env bash
# Session-end ingest hook for the swarm memory pipeline.
# Generated by bootstrap__swarm-memory. The coordinator substitutes
# {session_id} and runs this with /bin/sh -c; exit code 0 = ingested.
set -euo pipefail

SESSION_ID="\${1:?usage: ${HOOK_SCRIPT_NAME} <session_id>}"
COORDINATOR_URL="${settings.coordinatorUrl}"
LIBRARIAN_PERSONA="${LIBRARIAN_PERSONA_ID}"

# Claim the session first (ended → processing) so concurrent runs skip it.
drone-swarm --coordinator "$COORDINATOR_URL" session process "$SESSION_ID" > /dev/null

# Read the --- Turn N --- transcript and queue it to a headless librarian.
transcript_json="$(drone-swarm --coordinator "$COORDINATOR_URL" session transcript "$SESSION_ID")"
kickoff="$(printf '%s' "$transcript_json" | ${TRANSCRIPT_TO_KICKOFF})"

if printf '%s\\n' "$kickoff" | drone-agent --output-json --once --persona "$LIBRARIAN_PERSONA" > /dev/null 2>&1; then
  drone-swarm --coordinator "$COORDINATOR_URL" session processed "$SESSION_ID" \\
    --summary "ingested into memory wiki by ${HOOK_SCRIPT_NAME}"
else
  echo "librarian agent failed for session $SESSION_ID (left in processing)" >&2
  exit 1
fi
`;
}

export function buildCatchupScript(settings: SwarmMemorySettings): string {
  return `#!/usr/bin/env bash
# Gradual catch-up ingest for the swarm memory pipeline.
# Generated by bootstrap__swarm-memory. Grabs ended sessions newest-first
# (batch limited) and feeds each through the session-end ingest hook.
set -euo pipefail

COORDINATOR_URL="${settings.coordinatorUrl}"
BATCH_LIMIT="${settings.batchLimit}"
INGEST_HOOK="$HOME/.drone-swarm-memory/bin/${HOOK_SCRIPT_NAME}"

sessions_json="$(drone-swarm --coordinator "$COORDINATOR_URL" session list --status ended --limit "$BATCH_LIMIT")"
ids="$(printf '%s' "$sessions_json" | node -e 'const fs=require("node:fs");const d=JSON.parse(fs.readFileSync(0,"utf8"));for(const s of (d.sessions ?? []))process.stdout.write(String(s.id)+"\\n")')"

if [ -z "$ids" ]; then
  echo "catch-up: no ended sessions to ingest"
  exit 0
fi

failed=0
while IFS= read -r id; do
  [ -n "$id" ] || continue
  if ! bash "$INGEST_HOOK" "$id"; then
    echo "catch-up: ingest failed for session $id (continuing)" >&2
    failed=$((failed + 1))
  fi
done <<< "$ids"

echo "catch-up: batch complete ($failed failure(s))"
exit 0
`;
}

export function mergeSessionEndTrigger(
  existingRaw: string | undefined,
  hookPath: string
): unknown {
  const existing =
    existingRaw !== undefined ? (JSON.parse(existingRaw) as object) : {};
  return mergeConfig(existing, {
    sessionEnd: { type: 'command', command: `${hookPath} {session_id}` },
  });
}

export function cronLineFor(schedule: string, scriptPath: string): string {
  return `${schedule} bash ${scriptPath} >> $HOME/.drone-swarm-memory/catch-up.log 2>&1`;
}

async function confirm(
  elicit: DroneElicitation,
  id: string,
  prompt: string
): Promise<boolean> {
  const answers = await elicit.ask([
    {
      id,
      prompt,
      choices: [
        { value: 'yes', label: 'Yes — apply it' },
        { value: 'no', label: 'No — stop here' },
      ],
      defaultValue: 'no',
    },
  ]);
  return answers[id] === 'yes';
}

async function detectLaunchMode(runner: CommandRunner): Promise<Discovery['launchMode']> {
  const systemd = await runner(['systemctl', 'status', 'drone-coordinator']);
  if (systemd.code === 0 || systemd.code === 3) {
    return 'systemd';
  }
  const docker = await runner([
    'docker',
    'ps',
    '--format',
    '{{.Names}} {{.Image}}',
  ]);
  if (docker.code === 0 && docker.stdout.includes('drone-coordinator')) {
    return 'docker';
  }
  return 'unknown';
}

async function probeCoordinator(
  runner: CommandRunner,
  url: string
): Promise<boolean> {
  const result = await runner([
    'drone-swarm',
    '--coordinator',
    url,
    'session',
    'list',
    '--limit',
    '1',
  ]);
  return result.code === 0;
}

async function discover(
  elicit: DroneElicitation,
  runner: CommandRunner,
  home: string
): Promise<Discovery | undefined> {
  const reachableDefault = await probeCoordinator(
    runner,
    DEFAULT_COORDINATOR_URL
  );
  const answers = await elicit.ask([
    {
      id: 'coordinatorUrl',
      prompt: `Swarm memory setup. I detected the coordinator ${
        reachableDefault ? 'REACHABLE' : 'NOT reachable'
      } at ${DEFAULT_COORDINATOR_URL}.\n\nWhich URL should the pipeline talk to?`,
      freeform: true,
      placeholder: DEFAULT_COORDINATOR_URL,
      defaultValue: DEFAULT_COORDINATOR_URL,
    },
    {
      id: 'configureBeacon',
      prompt:
        'Also configure the beacon layer (a sessionEnd trigger at the beacon fires even when the coordinator is unreachable)?',
      choices: [
        { value: 'no', label: 'No — coordinator only (recommended)' },
        { value: 'yes', label: 'Yes — beacon too' },
      ],
      defaultValue: 'no',
    },
    {
      id: 'batchLimit',
      prompt: 'Catch-up job: how many ended sessions per run (newest first)?',
      freeform: true,
      placeholder: DEFAULT_BATCH_LIMIT,
      defaultValue: DEFAULT_BATCH_LIMIT,
    },
    {
      id: 'cronSchedule',
      prompt: 'Cron schedule for the catch-up job?',
      freeform: true,
      placeholder: DEFAULT_CRON_SCHEDULE,
      defaultValue: DEFAULT_CRON_SCHEDULE,
    },
  ]);

  const url = (
    (answers.coordinatorUrl as string) || DEFAULT_COORDINATOR_URL
  ).trim();
  const settings: SwarmMemorySettings = {
    coordinatorUrl: url,
    configureBeacon: answers.configureBeacon === 'yes',
    batchLimit: ((answers.batchLimit as string) || '').trim() || DEFAULT_BATCH_LIMIT,
    cronSchedule: ((answers.cronSchedule as string) || '').trim() || DEFAULT_CRON_SCHEDULE,
  };
  if (!/^\*\/\d+|^\d+/.test(settings.cronSchedule)) {
    return undefined;
  }

  return {
    settings,
    coordinatorReachable: await probeCoordinator(runner, url),
    launchMode: await detectLaunchMode(runner),
    coordinatorConfigPath: coordinatorConfigPath(home),
    beaconConfigPath: beaconConfigPath(home),
    coordinatorConfigRaw: await readIfPresent(coordinatorConfigPath(home)),
    beaconConfigRaw: await readIfPresent(beaconConfigPath(home)),
  };
}

async function restartServer(
  elicit: DroneElicitation,
  runner: CommandRunner,
  discovery: Discovery,
  server: 'coordinator' | 'beacon',
  pendingRestart: string[]
): Promise<void> {
  if (discovery.launchMode === 'unknown') {
    pendingRestart.push(
      `${server}: launch mode not detected — restart it yourself to activate the config`
    );
    return;
  }
  const command =
    discovery.launchMode === 'systemd'
      ? `systemctl restart ${server}`
      : `docker restart ${server}`;
  const approved = await confirm(
    elicit,
    `restart-${server}`,
    `The ${server} must restart to load the new config (launch mode: ${discovery.launchMode}).\n\nRun: ${command}`
  );
  if (!approved) {
    pendingRestart.push(`${server}: restart pending (declined) — run: ${command}`);
    return;
  }
  const result = await runner(command.split(' '));
  if (result.code !== 0) {
    pendingRestart.push(
      `${server}: restart command failed (${result.code}): ${result.stderr.trim()}`
    );
    return;
  }
  if (server === 'coordinator') {
    discovery.coordinatorReachable = await probeCoordinator(
      runner,
      discovery.settings.coordinatorUrl
    );
  }
}

async function installServerConfig(
  elicit: DroneElicitation,
  server: 'coordinator' | 'beacon',
  filePath: string,
  existingRaw: string | undefined,
  hookPath: string,
  reports: StepReport[]
): Promise<void> {
  const merged = mergeSessionEndTrigger(existingRaw, hookPath);
  const problems = validateConfigFile(merged);
  if (problems.length > 0) {
    reports.push({
      step: `config-${server}`,
      status: 'failed',
      detail: `merged config invalid: ${problems.join('; ')}`,
    });
    return;
  }
  const showBefore = existingRaw ? '(existing file)' : '(new file)';
  const approved = await confirm(
    elicit,
    `write-config-${server}`,
    `Write the sessionEnd trigger to ${filePath}?\n\nBefore: ${showBefore}\nAfter:\n\n${JSON.stringify(merged, null, 2)}\n\nTakes effect when the ${server} restarts.`
  );
  if (!approved) {
    reports.push({
      step: `config-${server}`,
      status: 'skipped',
      detail: 'user declined',
    });
    return;
  }
  await atomicWrite(filePath, `${JSON.stringify(merged, null, 2)}\n`);
  reports.push({ step: `config-${server}`, status: 'done', detail: filePath });
}

async function installCronEntry(
  elicit: DroneElicitation,
  runner: CommandRunner,
  discovery: Discovery,
  catchupPath: string,
  reports: StepReport[]
): Promise<void> {
  const line = cronLineFor(discovery.settings.cronSchedule, catchupPath);
  const existing = await runner(['crontab', '-l']);
  const currentCrontab =
    existing.code === 0 ? existing.stdout : '# (no crontab yet)';
  const updated = existing.code === 0 ? `${existing.stdout.trimEnd()}\n${line}\n` : `${line}\n`;

  const approved = await confirm(
    elicit,
    'write-cron',
    `Install the catch-up cron entry?\n\nBefore:\n${currentCrontab}\n\nAfter (appending last line):\n${line}\n\nSchedule: ${discovery.settings.cronSchedule}`
  );
  if (!approved) {
    reports.push({ step: 'cron', status: 'skipped', detail: 'user declined' });
    return;
  }
  const install = await runner(['crontab', '-'], { input: updated });
  if (install.code !== 0) {
    reports.push({
      step: 'cron',
      status: 'failed',
      detail: `crontab install failed: ${install.stderr.trim()}`,
    });
    return;
  }
  reports.push({ step: 'cron', status: 'done', detail: line });
}

async function smokeTest(
  elicit: DroneElicitation,
  runner: CommandRunner,
  discovery: Discovery,
  hookPath: string,
  reports: StepReport[]
): Promise<void> {
  const listing = await runner([
    'drone-swarm',
    '--coordinator',
    discovery.settings.coordinatorUrl,
    'session',
    'list',
    '--status',
    'ended',
    '--limit',
    '5',
  ]);
  if (listing.code !== 0) {
    reports.push({
      step: 'smoke',
      status: 'skipped',
      detail: 'could not list ended sessions (coordinator unreachable?)',
    });
    return;
  }
  const endedIds = listing.stdout
    .trim()
    .split('\n')
    .join(' ')
    .match(/"id"\s*:\s*"([^"]+)"/g)
    ?.map(m => m.replace(/"id"\s*:\s*"/, '').replace('"', ''))
    .slice(0, 5);

  const approved = await confirm(
    elicit,
    'smoke',
    `Smoke test on REAL conversations?\n\nEnded sessions available: ${
      endedIds && endedIds.length > 0 ? endedIds.join(', ') : '(none)'
    }\n\nSide effects: the chosen session is permanently marked processed and real wiki pages are written (editable afterward). This runs the same path production uses.`
  );
  if (!approved) {
    reports.push({ step: 'smoke', status: 'skipped', detail: 'user declined' });
    return;
  }

  const answer = await elicit.ask([
    {
      id: 'smokeSessionId',
      prompt: 'Which ended session should I push through the hook?',
      freeform: true,
      placeholder: endedIds?.[0] ?? '',
      defaultValue: endedIds?.[0] ?? '',
    },
  ]);
  const smokeId = ((answer.smokeSessionId as string) || '').trim();
  if (!smokeId) {
    reports.push({
      step: 'smoke',
      status: 'skipped',
      detail: 'no session id given',
    });
    return;
  }
  const run = await runner(['bash', hookPath, smokeId]);
  if (run.code !== 0) {
    reports.push({
      step: 'smoke',
      status: 'failed',
      detail: `ingest hook failed: ${run.stderr.trim() || `exit ${run.code}`}`,
    });
    return;
  }
  const wiki = await runner([
    'drone-swarm',
    '--coordinator',
    discovery.settings.coordinatorUrl,
    'wiki',
    'search',
    smokeId,
  ]);
  reports.push({
    step: 'smoke',
    status: 'done',
    detail: `session ${smokeId} ingested; wiki search exit ${wiki.code}`,
  });
}

async function runStaticValidation(
  runner: CommandRunner,
  discovery: Discovery,
  hookPath: string,
  catchupPath: string,
  reports: StepReport[]
): Promise<void> {
  for (const script of [hookPath, catchupPath]) {
    const check = await runner(['bash', '-n', script]);
    reports.push(
      check.code === 0
        ? { step: `bash-n:${path.basename(script)}`, status: 'done', detail: 'syntax ok' }
        : {
            step: `bash-n:${path.basename(script)}`,
            status: 'failed',
            detail: check.stderr.trim(),
          }
    );
  }
  const coordinatorRaw = await readIfPresent(discovery.coordinatorConfigPath);
  if (coordinatorRaw !== undefined) {
    const problems = validateConfigFile(JSON.parse(coordinatorRaw) as object);
    reports.push(
      problems.length === 0
        ? { step: 'validate-config-coordinator', status: 'done' }
        : {
            step: 'validate-config-coordinator',
            status: 'failed',
            detail: problems.join('; '),
          }
    );
  }
  const crontab = await runner(['crontab', '-l']);
  const cronOk = crontab.code === 0 && crontab.stdout.includes(path.basename(catchupPath));
  reports.push({
    step: 'cron-present',
    status: cronOk ? 'done' : 'failed',
    detail: cronOk ? undefined : 'catch-up entry not found in crontab',
  });
}

export type SwarmMemoryWorkflowOptions = {
  runner?: CommandRunner;
  home?: string;
};

export function createSwarmMemoryWorkflow(
  options: SwarmMemoryWorkflowOptions = {}
): DroneWorkflow {
  const runner = options.runner ?? createExecFileRunner();
  return {
    name: 'swarm-memory',
    description:
      'Set up the swarm memory pipeline on this coordinator host: sessionEnd ingest hook, cron catch-up job, server config triggers, and the wiki-librarian persona. Checks in before every change.',
    inputSchema: {
      type: 'object',
      properties: {},
      additionalProperties: false,
    },
    run: async (_input, ctx) => {
      const reports: StepReport[] = [];
      const pendingRestart: string[] = [];
      const home = options.home ?? os.homedir();

      const discovery = await discover(ctx.elicit, runner, home);
      if (!discovery) {
        return {
          toolResult: JSON.stringify(
            { ok: false, message: 'Setup cancelled: invalid cron schedule.' },
            null,
            2
          ),
        };
      }

      if (!discovery.coordinatorReachable) {
        return {
          toolResult: JSON.stringify(
            {
              ok: false,
              message: `Coordinator at ${discovery.settings.coordinatorUrl} is not reachable. Start it (or fix the URL) and run the workflow again.`,
            },
            null,
            2
          ),
        };
      }

      // Hook script
      const hookPath = hookScriptPath(home);
      const hookScript = buildHookScript(discovery.settings);
      if (
        await confirm(
          ctx.elicit,
          'write-hook',
          `Create the session-end ingest hook script?\n\n${hookPath}\n\n${hookScript}`
        )
      ) {
        await atomicWrite(hookPath, hookScript, 0o755);
        reports.push({ step: 'hook-script', status: 'done', detail: hookPath });
      } else {
        reports.push({
          step: 'hook-script',
          status: 'skipped',
          detail: 'user declined — stopping here',
        });
        return summarize(discovery, reports, pendingRestart, 'hook script declined');
      }

      // Catch-up script + cron
      const catchupPath = catchupScriptPath(home);
      const catchupScript = buildCatchupScript(discovery.settings);
      if (
        await confirm(
          ctx.elicit,
          'write-catchup',
          `Create the gradual catch-up script?\n\n${catchupPath}\n\n${catchupScript}`
        )
      ) {
        await atomicWrite(catchupPath, catchupScript, 0o755);
        reports.push({
          step: 'catchup-script',
          status: 'done',
          detail: catchupPath,
        });
        await installCronEntry(ctx.elicit, runner, discovery, catchupPath, reports);
      } else {
        reports.push({
          step: 'catchup-script',
          status: 'skipped',
          detail: 'user declined',
        });
      }

      // Server configs
      await installServerConfig(
        ctx.elicit,
        'coordinator',
        discovery.coordinatorConfigPath,
        discovery.coordinatorConfigRaw,
        hookPath,
        reports
      );
      if (discovery.settings.configureBeacon) {
        await installServerConfig(
          ctx.elicit,
          'beacon',
          discovery.beaconConfigPath,
          discovery.beaconConfigRaw,
          hookPath,
          reports
        );
      }

      // Restarts (ask-first)
      await restartServer(
        ctx.elicit,
        runner,
        discovery,
        'coordinator',
        pendingRestart
      );
      if (discovery.settings.configureBeacon) {
        await restartServer(
          ctx.elicit,
          runner,
          discovery,
          'beacon',
          pendingRestart
        );
      }

      // Static validation (always)
      await runStaticValidation(runner, discovery, hookPath, catchupPath, reports);

      // Smoke (confirm-first, real conversations)
      await smokeTest(ctx.elicit, runner, discovery, hookPath, reports);

      return summarize(discovery, reports, pendingRestart, 'completed');
    },
  };
}

function summarize(
  discovery: Discovery,
  reports: StepReport[],
  pendingRestart: string[],
  outcome: string
): { toolResult: string; kickMessage?: string } {
  const failed = reports.filter(r => r.status === 'failed');
  const result = {
    ok: failed.length === 0,
    outcome,
    steps: reports,
    pendingRestart,
    settings: discovery.settings,
  };
  const lines = [
    `Swarm memory bootstrap ${outcome}.`,
    '',
    ...reports.map(
      r => `- ${r.step}: ${r.status}${r.detail ? ` — ${r.detail}` : ''}`
    ),
  ];
  if (pendingRestart.length > 0) {
    lines.push('', 'Pending restarts:');
    for (const item of pendingRestart) {
      lines.push(`- ${item}`);
    }
  }
  lines.push(
    '',
    'Sessions move active → stale → ended → processing → processed; the hook claims ended sessions and the catch-up script sweeps the queue hourly.'
  );
  return {
    toolResult: JSON.stringify(result, null, 2),
    kickMessage: lines.join('\n'),
  };
}